### ISSUE TITLE
Dados de Mock do híbrido

### ISSUE THREAD

**Issue by PatrickSampaioUSP** [Projeto-Jupiter/PyInstrumentation#5]
Para podermos fazer a interface de instrumentação do híbrido são mandatórios dados de mock, crie estes dados.

**Comment by jaopropulseiro** [comment]
O mock seria no caso só dá curva de empuxo à princípio?

**Comment by PatrickSampaioUSP** [comment]
Não só a curva de empuxo, mas dos outros dados que vamos querer do hibrido. Por exemplo a curva de pressão do transdutor de pressão ou a curva de temperatura do termopar... Ai temos que olhar aquela reunião e ver quais sensores são discreto, e plotar uma curva, caso necessário, ou apenas exibir um SIM/NAO na tela caso discreto
